### PR TITLE
Add support for bitcoind@0.14.1

### PR DESCRIPTION
**Pull request by pedrobranco**
This PR adds support for `bitcoind` version `0.14.1`.

### CODE REVIEW

**Comment by yangwao** [comment]
bump?

**Comment by ruimarinho** [comment]
@yangwao sorry for the lack of feedback, but something's fishy. If you take a look at https://travis-ci.org/seegno/docker-bitcoind/jobs/240583779#L1140, the hashes don't match. Let me try and find the reason for this before merging 0.14.1.

**Comment by yangwao** [comment]
@ruimarinho see. Looks like here is shasum hardcoded hmm https://github.com/seegno/docker-bitcoind/pull/25/files#diff-7e3c530571e5d1977f61accf9a838000R12

**Comment by ruimarinho** [comment]
@yangwao exactly, that's what ensures that the file hasn't been tampered with. I'm switching to the `.tar.gz` which is published on the bitcoin.org website as I can read the hash from the SHA256SUM signed file.

**Comment by ruimarinho** [comment]
@pedrobranco, deprecating this PR in favour of https://github.com/seegno/docker-bitcoind/pull/29 which brings additional changes to the alpine-based Dockerfile.

**Pull request closed without merging**
